export const autohistCopy = {
  hero: {
    eyebrow: "AUTOHIST",
    title: "O histórico começa antes do problema.",
    subtitle:
      "Cada manutenção deixa um registro. O AutoHist preserva a memória completa do veículo — com clareza e continuidade.",
    cta: { label: "Conhecer o AutoHist", href: "#centralizacao" },
    status: "Em desenvolvimento",
    note: "Prontuário digital do veículo.",
  },
  problem: {
    eyebrow: "01 — O problema",
    title: "A informação do veículo fica espalhada.",
    body: "WhatsApp, fotos, papel, memória do mecânico, o que o cliente descreve. Fragmentos em lugares diferentes. Nenhuma visão completa.",
    aside: "Desconectado.",
    fragments: [
      { id: "whatsapp", label: "WhatsApp" },
      { id: "fotos", label: "Fotos" },
      { id: "papel", label: "Papel" },
      { id: "memoria", label: "Memória" },
      { id: "cliente", label: "Cliente" },
    ],
  },
  converge: {
    eyebrow: "02 — Centralização",
    title: "Tudo converge para um único histórico.",
    body: "Placa, veículo, oficina e registros se encontram na mesma linha. Uma memória compartilhada — não cópias paralelas.",
    aside: "Um prontuário.\nUma continuidade.",
    nodes: [
      { id: "placa", label: "Placa" },
      { id: "veiculo", label: "Veículo" },
      { id: "oficina", label: "Oficina" },
      { id: "registro", label: "Registro" },
    ],
  },
  flow: {
    eyebrow: "03 — Como funciona",
    title: "Quatro passos. Uma memória permanente.",
    body: "Do cadastro ao histórico — o fluxo é linear, preciso e sem ruído.",
    steps: [
      {
        id: "cadastro",
        index: "01",
        title: "Cadastrar veículo",
        detail: "Placa, modelo e identificação inicial.",
        screen: "cropPlaca" as const,
        caption: "Nova OS — identificação por placa",
      },
      {
        id: "servico",
        index: "02",
        title: "Adicionar serviço",
        detail: "Diagnóstico, peças e quilometragem.",
        screen: "cropServico" as const,
        caption: "Quilometragem, tipo e responsável",
      },
      {
        id: "fotos",
        index: "03",
        title: "Registrar fotos",
        detail: "Evidência visual anexada ao evento.",
        screen: null,
        caption: "Captura de evidências — aguardando tela real",
      },
      {
        id: "historico",
        index: "04",
        title: "Histórico permanente",
        detail: "Tudo permanece. Nada se perde.",
        screen: "cropHistorico" as const,
        caption: "Histórico geral de ordens",
      },
    ],
  },
  search: {
    eyebrow: "04 — Busca inteligente",
    title: "Pesquisar a placa. Abrir a história.",
    body: "Serviços, fotos, quilometragem e PDF — acessíveis no instante em que a placa é encontrada.",
    aside: "Velocidade com precisão.",
    plate: "PRD4H60",
    results: ["Serviços", "Fotos", "Quilometragem", "PDF"],
    stages: [
      {
        id: "digitada",
        label: "Placa",
        screen: "cropBusca" as const,
        caption: "Filtros e busca por placa",
      },
      {
        id: "resultado",
        label: "Histórico",
        screen: "cropHistorico" as const,
        caption: "Ordens encontradas por placa",
      },
      {
        id: "pdf",
        label: "PDF",
        screen: "cropPdf" as const,
        caption: "Exportar PDF do histórico",
      },
    ],
  },
  timeline: {
    eyebrow: "05 — Linha do tempo",
    title: "A vida do veículo, em sequência.",
    body: "Cada manutenção, revisão, troca e documento permanece encadeado — legível ao longo dos anos.",
    events: [
      { id: "e1", label: "Entrada", detail: "Leitura inicial", km: "12.400 km", proof: null },
      {
        id: "e2",
        label: "Revisão",
        detail: "Óleo e filtros",
        km: "28.900 km",
        proof: "cropHistorico" as const,
      },
      {
        id: "e3",
        label: "Troca",
        detail: "Pastilhas",
        km: "41.200 km",
        proof: "cropServico" as const,
      },
      { id: "e4", label: "Inspeção", detail: "Diagnóstico", km: "56.780 km", proof: null },
      {
        id: "e5",
        label: "Documento",
        detail: "Laudo PDF",
        km: "62.540 km",
        proof: "cropPdf" as const,
      },
      { id: "e6", label: "Continuidade", detail: "Próximo ciclo", km: "—", proof: null },
    ],
  },
  trust: {
    eyebrow: "06 — Confiança",
    title: "O que permanece quando o serviço termina.",
    items: [
      { id: "t1", label: "Histórico permanente" },
      { id: "t2", label: "Organização" },
      { id: "t3", label: "Transparência" },
      { id: "t4", label: "Continuidade" },
      { id: "t5", label: "Segurança" },
      { id: "t6", label: "Compartilhamento" },
    ],
  },
  closing: {
    eyebrow: "AutoHist",
    line: "O histórico continua.\nA confiança também.",
    note: "Prontuário digital do veículo.",
    primaryCta: { label: "Conhecer o AutoHist", href: "/contato" },
    secondaryCta: { label: "Ver todos os produtos", href: "/produtos" },
  },
} as const;
